### ISSUE TITLE
runtime custom_menu

### ISSUE THREAD

**Issue by eouia** [shbatm/MMM-Remote-Control#4]
Nice work @shbatm 
I have some suggestions and more.

`custom_menu.json` : 
I think it would be nicer if dynamic registering custom menus  from modules on runtime would be supported. Making custom_menu seems not so easy to usual users. I think module developers have to support it.

My MMM-TelegramBot uses that pattern. Modules can register it's commands(or menu) to be used in MMM-TelegramBot. If your PR would support similar feature, I will modify my modules to support it to be compatible with MMM-Remote-Control.
https://github.com/eouia/MMM-TelegramBot/wiki/How-to-add-commands

I believe it could be done by adding menu JSON object received from modules with `ADD_CUSTOM_MENU` notification. Each module just sends it's menu JSON object with that notification when module is ready.
Or, with register callback function could be another option like MMM-TelegramBot.(I prefer it)

Second thing is about Module Control(discovery/guessing).
Some modules of mine are using CONSTANTS or configurable values as notification names. In that case, Discovery/Guessing won't work properly. I think registration method also should be supported.

Have a nice day!

**Comment by shbatm** [comment]
@eouia, this is supported in the Module Control dynamic menu, and Explicit API parts. You can send a notification to register/overwrite the guessed functions. I'll admit it's not fully tested, but what you described is exactly the intent. 

See this: https://github.com/shbatm/MMM-Remote-Control/blob/upstream_pr/API/README.md#3-external-apis-explicit---extending-another-module-with-this-api

**Comment by eouia** [comment]
Nice to hear it. I'm waiting PR merging to work my module being compatible.
Thanks again for nice work.
